### ISSUE TITLE
What vim color scheme is used in the screenshot on the front page?

### ISSUE THREAD

**Issue by kergoth** [way-cooler/way-cooler.github.io#1]
A bit random, I'm sure, but I quite like the scheme used in the screenshot :)

**Comment by Timidger** [comment]
I _believe_ it's just the default? To my great shame I've been using Emacs (with evil bindings!) much more lately so I'm not sure what the color scheme actually is.

I'll check after work, assuming I didn't change it.

**Comment by Timidger** [comment]
Sorry for the delay! I lost the theme so I don't remember what it is, sorry.
